TP2/TETRA/config/routes.rb
Rails.application.routes.draw do
    root to: 'dashboard#index'
    resources :query, only: [:show, :index]
end

TP2/TETRA/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TP2/TETRA/app/models/event.rb
class Event < ActiveRecord::Base
  self.table_name = 'Event'
  self.primary_key = :event_id

  has_many :talks, class_name: 'Talk', foreign_key: :event_id
end

TP2/TETRA/app/models/rating.rb
class Rating < ActiveRecord::Base
  self.table_name = 'Rating'
  self.primary_key = :rating_id

  has_many :talk_ratings, class_name: 'TalkRating', foreign_key: :rating_id
end

TP2/TETRA/app/models/related_talk.rb
class RelatedTalk < ActiveRecord::Base
  self.table_name = 'Related_Talks'
  self.primary_key = %i[talk1_id talk2_id]

  belongs_to :talk, class_name: 'Talk', foreign_key: :talk1_id
  belongs_to :talk, class_name: 'Talk', foreign_key: :talk2_id
end

TP2/TETRA/app/models/speaker.rb
class Speaker < ActiveRecord::Base
  self.table_name = 'Speaker'
  self.primary_key = :speaker_id

  has_many :talks, class_name: 'Talk', foreign_key: :speaker_id
end

TP2/TETRA/app/models/tag.rb
class Tag < ActiveRecord::Base
  self.table_name = 'Tag'
  self.primary_key = :tag_id

  has_many :talk_tags, class_name: 'TalkTag', foreign_key: :tag_id
end

TP2/TETRA/app/models/talk.rb
class Talk < ActiveRecord::Base
  self.table_name = 'Talk'
  self.primary_key = :talk_id

  has_many :related_talks, class_name: 'RelatedTalk'
  has_many :related_talks, class_name: 'RelatedTalk'
  belongs_to :event, class_name: 'Event', foreign_key: :event_id
  belongs_to :speaker, class_name: 'Speaker', foreign_key: :speaker_id
  has_many :talk_ratings, class_name: 'TalkRating', foreign_key: :talk_id
  has_many :talk_tags, class_name: 'TalkTag', foreign_key: :talk_id
end

TP2/TETRA/app/models/talk_rating.rb
class TalkRating < ActiveRecord::Base
  self.table_name = 'Talk_Rating'
  self.primary_key = %i[talk_id rating_id]

  belongs_to :rating, class_name: 'Rating', foreign_key: :rating_id
  belongs_to :talk, class_name: 'Talk', foreign_key: :talk_id
end

TP2/TETRA/app/models/talk_tag.rb
class TalkTag < ActiveRecord::Base
  self.table_name = 'Talk_Tag'
  self.primary_key = %i[talk_id tag_id]

  belongs_to :tag, class_name: 'Tag', foreign_key: :tag_id
  belongs_to :talk, class_name: 'Talk', foreign_key: :talk_id
end

TP2/TETRA/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :set_locale, :basic_queries, :report_queries, :transcript_queries

    def set_locale
        I18n.locale = params[:locale] || I18n.default_locale
    end

    def basic_queries
        # The queries from 01 to 10 are the basic, required queries
        @basic_queries ||= query_options[0..8]
    end

    def report_queries
        # The queries from 11 to 13 are part of advanced characteristic: report queries
        @report_queries ||= query_options[9..11]
    end

    def transcript_queries
        # The queries from 14 to 17 are part of advanced characteristic: text queries
        @transcript_queries ||= query_options[12..15]
    end

    private

    def query_options
        @query_options ||= Dir.entries('./app/assets/sql_queries/')
                              .reject { |f| File.directory? f }
                              .sort
    end
end

TP2/TETRA/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        query_options
    end

    def query_options
        @query_options ||= Dir.entries("./app/assets/sql_queries/")
                              .reject { |f| File.directory? f }
                              .sort
    end
end

TP2/TETRA/app/controllers/query_controller.rb
class QueryController < ApplicationController
    def show
        set_query

        @query_result ||= ActiveRecord::Base.connection.select_all(set_query)
        @query_successful = @query_result.is_a? ActiveRecord::Result

        return unless @query_successful
        @html = syntax_query(@set_query)
        set_columns_and_rows
    end

    private

    def set_columns_and_rows
        @columns = @query_result.columns
        @rows = @query_result.rows
        @columns_num = @columns.size
        @rows_num = @rows.size
    end

    def syntax_query(code)
        CodeRay.scan(code, :sql).div(line_numbers: :table)
    end

    def coderay(text)
        text.gsub(/\<code( lang="(.+?)")?\>(.+?)\<\/code\>/m) do
            CodeRay.scan(Regexp.last_match(3), Regexp.last_match(2)).div(css: :class)
        end
    end

    def set_query
        @query_num ||= params[:id].to_s.rjust(2, '0')
        @set_query ||= IO.read("./app/assets/sql_queries/query_#{@query_num}.sql")
    end
end

TP2/TETRA/app/helpers/application_helper.rb
module ApplicationHelper
end

TP2/TETRA/app/views/dashboard/index.html.erb
<div class="row">
    <img class="col s4 materialboxed" data-caption="Diagrama ER" src="assets/ER.png">
    <div class="col s4">
        <div style="text-align: center;" class="card indigo lighten-3 ">
            <div class="card-content black-text">
                <span class="card-title"><b><span style="color: red">TE.</span>T.R.A.</b></span>
                <p ><span style="color: red">TED</span> Talks Rails Application</p>
            </div>
        </div>
        <div style="text-align: center;" class="card indigo lighten-3 ">
            <div class="card-content black-text">
                <p>Este trabalho de Introdução à Banco de Dados</p>
                <p>
                    está disponível no
                    <a style="color: blue" href="http://homepages.dcc.ufmg.br/~mirella/doku.php?id=dcc011:main">site</a>
                    da Professora Mirella
                </p>
            </div>
        </div>
        <div style="text-align: center;" class="card indigo lighten-3 ">
            <div class="card-content black-text">
                <p>
O objetivo deste trabalho é projetar e implementar um banco de dados relacional para
realizar consultas interessantes. O projeto do banco de dados deverá seguir o processo
apresentado em aula. Em particular, deverão ser  apresentados  o  diagrama
entidade-relacionamento e  o  esquema  relacional  referente  ao  banco  de  dados
projetado. O banco de dados deverá ser instanciado com dados reais (de preferência)
ou gerados sinteticamente. Consultas deverão ser realizadas sobre o banco.
                </p>
            </div>
        </div>
    </div>
    <img class="col s4 materialboxed" data-caption="Modelo Relacional" src="assets/Modelo_Relacional.png">
</div>

<script>
$(document).ready(function(){
   $('.materialboxed').materialbox();
 });
</script>

TP2/TETRA/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TETRA</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <ul id='dropdown1' class='dropdown-content'>
        <% @basic_queries.each_with_index do |item,index| %>
            <li>
                <%= link_to query_path(index+1) do %>
                    <%= index+1 %> -
                    <%= I18n.t("queries.name.q_#{(index+1).to_s.rjust(2, '0')}") %>
                <% end %>
            </li>
        <% end %>
    </ul>
    <ul id='dropdown2' class='dropdown-content'>
        <% @report_queries.each_with_index do |item,index| %>
            <li>
                <%= link_to query_path(index+11) do %>
                    <%= index+11 %> - <%= I18n.t("queries.name.q_#{(index+11)}") %>
                <% end %>
            </li>
        <% end %>
    </ul>
    <ul id='dropdown3' class='dropdown-content'>
        <% @transcript_queries.each_with_index do |item,index| %>
            <li>
                <%= link_to query_path(index+14) do %>
                    <%= index+14 %> - <%= I18n.t("queries.name.q_#{(index+14)}") %>
                <% end %>
            </li>
        <% end %>
    </ul>
    <nav>
      <div class="nav-wrapper row">
        <div class="col s2">
          <%= link_to 'Retornar ao Menu', root_path %>
        </div>
        <ul class="center hide-on-med-and-down">
          <li class="col s4">
              <a class="dropdown-button" data-beloworigin="true" data-activates='dropdown1'>
                  Escolha uma das consultas básicas<i class="material-icons right">arrow_drop_down</i>
              </a>
          </li>
          <li class="col s4">
              <a class="dropdown-button" data-beloworigin="true" data-activates='dropdown2'>
                  Escolha uma das consultas tipo relatório<i class="material-icons right">arrow_drop_down</i>
              </a>
          </li>
          <li class="col s2">
              <a class="dropdown-button" data-beloworigin="true" data-activates='dropdown3'>
                  Dados Não-Convencionais<i class="material-icons right">arrow_drop_down</i>
              </a>
          </li>
        </ul>
      </div>
    </nav>

    <script>
    $(document).ready(function () {
        $(".dropdown-button").dropdown({hover: false});
    });
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TP2/TETRA/app/views/query/show.html.erb
<% unless @query_successful %>
    <div class="row">
        <div class="col s4 offset-s4">
            <div style="text-align: center;" class="card indigo lighten-2 ">
                <div class="card-content black-text">
                    <p style="color: red">A consulta está errada! Por favor verifique a sintaxe</p>
                </div>
            </div>
        </div>
    </div>
<% else %>
    <div class="row">
        <div class="col s4">
            <div style="text-align: center;" class="card indigo lighten-2 ">
                <div class="card-content black-text">
                    <span class="card-title"><b>A consulta escolhida foi:</b></span>
                    <p>
                        <%= I18n.t("queries.name.q_#{@query_num}") %>
                    </p>
                </div>
            </div>
        </div>
        <div class="col s4">
            <div style="text-align: center;" class="card indigo lighten-2 ">
                <div class="card-content black-text">
                    <span class="card-title"><b>Essa consulta é do tipo:</b></span>
                    <p>
                        <%= I18n.t("queries.type.t_#{@query_num}") %>
                    </p>
                </div>
            </div>
        </div>
        <div class="col s4">
            <div style="text-align: center;" class="card indigo lighten-2 ">
                <div class="card-content black-text">
                    <span class="card-title"><b>A consulta retornou:</b></span>
                    <p><%= @columns_num %> colunas</p>
                    <p><%= @rows_num %> linhas</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s8 offset-s4">
            <%= @html.html_safe %>
        </div>
    </div>
    <table class="responsive-table centered striped bordered">
        <thead>
            <tr>
                <% @columns.each_with_index do |column_item,index| %>
                <th> <%= column_item %></th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @rows.each do |row_item| %>
            <tr>
                <% (0..@columns_num).each do |index| %>
                <td> <%= row_item[index] %> </td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
<% end %>